---
version: "3.7"

services:

  postgres:
    image: bitnami/postgresql:10
    container_name: postgres
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - ./postgresql:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=supersecret
      - POSTGRESQL_DATABASE=kv_demo

  redis:
    image: bitnami/redis:5.0.4-debian-9-r40
    container_name: redis
    ports:
      - '0.0.0.0:6379:6379'
    volumes:
      - ./redis:/bitnami/redis
    environment:
      - REDIS_PASSWORD=supersecret
